version: "3.8"

services:
  django:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: "on-failure"
    env_file:
      - ./.env
    environment:
      - "DJANGO_SECRET_KEY=127ekbdpc-k%2le)*=964)mwsz56&k@%3-8jl_t9#+q3s+)hf^"
      - "DJANGO_DEBUG=True"

  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/posgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:

